/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CursoRouteImport } from './routes/curso'
import { Route as CalibracaoRouteImport } from './routes/calibracao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursoIndexRouteImport } from './routes/curso.index'
import { Route as CursoModuleIdIndexRouteImport } from './routes/curso.$moduleId.index'
import { Route as CursoModuleIdLessonIdRouteImport } from './routes/curso.$moduleId.$lessonId'

const CursoRoute = CursoRouteImport.update({
  id: '/curso',
  path: '/curso',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibracaoRoute = CalibracaoRouteImport.update({
  id: '/calibracao',
  path: '/calibracao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoIndexRoute = CursoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursoRoute,
} as any)
const CursoModuleIdIndexRoute = CursoModuleIdIndexRouteImport.update({
  id: '/$moduleId/',
  path: '/$moduleId/',
  getParentRoute: () => CursoRoute,
} as any)
const CursoModuleIdLessonIdRoute = CursoModuleIdLessonIdRouteImport.update({
  id: '/$moduleId/$lessonId',
  path: '/$moduleId/$lessonId',
  getParentRoute: () => CursoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calibracao': typeof CalibracaoRoute
  '/curso': typeof CursoRouteWithChildren
  '/curso/': typeof CursoIndexRoute
  '/curso/$moduleId/$lessonId': typeof CursoModuleIdLessonIdRoute
  '/curso/$moduleId/': typeof CursoModuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calibracao': typeof CalibracaoRoute
  '/curso': typeof CursoIndexRoute
  '/curso/$moduleId/$lessonId': typeof CursoModuleIdLessonIdRoute
  '/curso/$moduleId': typeof CursoModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calibracao': typeof CalibracaoRoute
  '/curso': typeof CursoRouteWithChildren
  '/curso/': typeof CursoIndexRoute
  '/curso/$moduleId/$lessonId': typeof CursoModuleIdLessonIdRoute
  '/curso/$moduleId/': typeof CursoModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calibracao'
    | '/curso'
    | '/curso/'
    | '/curso/$moduleId/$lessonId'
    | '/curso/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calibracao'
    | '/curso'
    | '/curso/$moduleId/$lessonId'
    | '/curso/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/calibracao'
    | '/curso'
    | '/curso/'
    | '/curso/$moduleId/$lessonId'
    | '/curso/$moduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalibracaoRoute: typeof CalibracaoRoute
  CursoRoute: typeof CursoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/curso': {
      id: '/curso'
      path: '/curso'
      fullPath: '/curso'
      preLoaderRoute: typeof CursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibracao': {
      id: '/calibracao'
      path: '/calibracao'
      fullPath: '/calibracao'
      preLoaderRoute: typeof CalibracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/': {
      id: '/curso/'
      path: '/'
      fullPath: '/curso/'
      preLoaderRoute: typeof CursoIndexRouteImport
      parentRoute: typeof CursoRoute
    }
    '/curso/$moduleId/': {
      id: '/curso/$moduleId/'
      path: '/$moduleId'
      fullPath: '/curso/$moduleId/'
      preLoaderRoute: typeof CursoModuleIdIndexRouteImport
      parentRoute: typeof CursoRoute
    }
    '/curso/$moduleId/$lessonId': {
      id: '/curso/$moduleId/$lessonId'
      path: '/$moduleId/$lessonId'
      fullPath: '/curso/$moduleId/$lessonId'
      preLoaderRoute: typeof CursoModuleIdLessonIdRouteImport
      parentRoute: typeof CursoRoute
    }
  }
}

interface CursoRouteChildren {
  CursoIndexRoute: typeof CursoIndexRoute
  CursoModuleIdLessonIdRoute: typeof CursoModuleIdLessonIdRoute
  CursoModuleIdIndexRoute: typeof CursoModuleIdIndexRoute
}

const CursoRouteChildren: CursoRouteChildren = {
  CursoIndexRoute: CursoIndexRoute,
  CursoModuleIdLessonIdRoute: CursoModuleIdLessonIdRoute,
  CursoModuleIdIndexRoute: CursoModuleIdIndexRoute,
}

const CursoRouteWithChildren = CursoRoute._addFileChildren(CursoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalibracaoRoute: CalibracaoRoute,
  CursoRoute: CursoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
